extends Node

const FLOOD := preload("res://Levels/Scenes/Dogana/boss_flood_surge.gd")


func _ready() -> void:
	var flood := FLOOD.new() as Area2D
	flood.call("setup", Vector2(900.0, 160.0), 1, 0.22, 0.7)
	add_child(flood)
	for _frame in 28:
		await get_tree().physics_frame
	if flood.find_children("*", "Sprite2D", true, false).size() > 0:
		return _fail("the physical flood still contains a wave sprite")
	var polygon := flood.get_node_or_null("PhysicalFloodVolume") as Polygon2D
	var surface := flood.get_node_or_null("PhysicalFloodSurface") as Line2D
	var bloom := flood.get_node_or_null("FloodBloom") as Line2D
	var droplets := flood.get_node_or_null("FloodDroplets") as CPUParticles2D
	var collision := flood.get_node_or_null("FloodCollision") as CollisionShape2D
	if polygon == null or polygon.polygon.size() < 40:
		return _fail("water volume is not generated by the spring surface")
	if surface == null or surface.points.size() < 40 or bloom == null:
		return _fail("physical surface or additive bloom is missing")
	if droplets == null or not droplets.emitting:
		return _fail("surface droplets did not activate")
	if collision == null or not (collision.shape is RectangleShape2D):
		return _fail("flood collision is missing")
	if (collision.shape as RectangleShape2D).size.y < 80.0:
		return _fail("collision did not rise from the floor with the water volume")
	var min_height := INF
	var max_height := -INF
	for point in surface.points:
		min_height = minf(min_height, point.y)
		max_height = maxf(max_height, point.y)
	if max_height - min_height < 1.0:
		return _fail("spring surface stayed perfectly flat")
	print("CALIGO_BOSS_PHYSICAL_FLOOD_OK: spring water, rising collision, bloom and droplets")
	get_tree().quit(0)


func _fail(message: String) -> void:
	push_error("BOSS_PHYSICAL_FLOOD_FAIL: %s" % message)
	get_tree().quit(1)
